In [7]:
import requests
import pandas as pd

appid = 578080  # PUBG

url = f"https://steamspy.com/api.php?request=appdetails&appid={appid}"

response = requests.get(url)
data = response.json()

data

{'appid': 578080,
 'name': 'PUBG: BATTLEGROUNDS',
 'developer': 'PUBG Corporation',
 'publisher': 'KRAFTON, Inc.',
 'score_rank': '',
 'positive': 1520457,
 'negative': 1037487,
 'userscore': 0,
 'owners': '100,000,000 .. 200,000,000',
 'average_forever': 0,
 'average_2weeks': 0,
 'median_forever': 0,
 'median_2weeks': 0,
 'price': '0',
 'initialprice': '0',
 'discount': '0',
 'ccu': 314682,
 'languages': 'English, Korean, Simplified Chinese, French, German, Spanish - Spain, Arabic, Japanese, Polish, Portuguese - Portugal, Russian, Turkish, Thai, Italian, Portuguese - Brazil, Traditional Chinese, Ukrainian',
 'genre': 'Action, Adventure, Massively Multiplayer, Free To Play',
 'tags': {'Survival': 14893,
  'Shooter': 12788,
  'Battle Royale': 10936,
  'Multiplayer': 10884,
  'FPS': 8483,
  'PvP': 7734,
  'Third-Person Shooter': 7341,
  'Action': 6044,
  'Online Co-Op': 5400,
  'Tactical': 5080,
  'Co-op': 4364,
  'First-Person': 4116,
  'Strategy': 3138,
  'Early Access': 2840,
  'Competitive': 2461,
  'Third Person': 2385,
  'Team-Based': 2108,
  'Difficult': 1766,
  'Simulation': 1411,
  'Stealth': 1310}}

In [8]:
import requests
import pandas as pd

url = "https://steamspy.com/api.php?request=top100in2weeks"

response = requests.get(url)
data = response.json()

df = pd.DataFrame.from_dict(data, orient='index')

df.head()

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
730,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,1013936
1172470,1172470,Apex Legends,Respawn,Electronic Arts,,668053,326926,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,124262
578080,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",,1520457,1037487,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,314682
1623730,1623730,Palworld,Pocketpair,Pocketpair,,358266,22443,0,"50,000,000 .. 100,000,000",0,0,0,0,2999,2999,0,18028
440,440,Team Fortress 2,Valve,Valve,,1044264,117208,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,43819

In [12]:
df.sort_values(
    by='average_forever',
    ascending=False
)[['name', 'average_forever']].head(20)

                                     name  average_forever
730      Counter-Strike: Global Offensive                0
10                         Counter-Strike                0
251570                      7 Days to Die                0
477160                    Human Fall Flat                0
239140                        Dying Light                0
322330              Don't Starve Together                0
550650                        Black Squad                0
1222670                        The Sims 4                0
400                                Portal                0
755790                    Ring of Elysium                0
3164500                        Schedule I                0
240                Counter-Strike: Source                0
444200               World of Tanks Blitz                0
1172470                      Apex Legends                0
386360                              SMITE                0
648800                               Raft                0
1240440                     Halo Infinite                0
1517290                  Battlefield 2042                0
1174180             Red Dead Redemption 2                0
1966720                    Lethal Company                0

In [15]:
print(df.columns.tolist())

['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu']

In [18]:
import requests

genres = set()

for page in range(3):  # 테스트용
    url = f"https://steamspy.com/api.php?request=all&page={page}"
    data = requests.get(url).json()

    for game in data.values():
        genre_str = game.get('genre')

        if genre_str:
            for g in genre_str.split(','):
                genres.add(g.strip())

print(sorted(genres))

[]

In [20]:
import requests

url = "https://steamspy.com/api.php?request=appdetails&appid=730"

data = requests.get(url).json()

print(data)

{'appid': 730, 'name': 'Counter-Strike: Global Offensive', 'developer': 'Valve', 'publisher': 'Valve', 'score_rank': '', 'positive': 7642084, 'negative': 1173003, 'userscore': 0, 'owners': '100,000,000 .. 200,000,000', 'average_forever': 0, 'average_2weeks': 0, 'median_forever': 0, 'median_2weeks': 0, 'price': '0', 'initialprice': '0', 'discount': '0', 'ccu': 1013936, 'languages': 'English, Czech, Danish, Dutch, Finnish, French, German, Hungarian, Italian, Japanese, Korean, Norwegian, Polish, Portuguese - Portugal, Portuguese - Brazil, Romanian, Russian, Simplified Chinese, Spanish - Spain, Swedish, Thai, Traditional Chinese, Turkish, Bulgarian, Ukrainian, Greek, Spanish - Latin America, Vietnamese, Indonesian', 'genre': 'Action, Free To Play', 'tags': {'FPS': 91172, 'Shooter': 65634, 'Multiplayer': 62536, 'Competitive': 53536, 'Action': 47634, 'Team-Based': 46549, 'e-sports': 43682, 'Tactical': 41468, 'First-Person': 39540, 'PvP': 34587, 'Online Co-Op': 34056, 'Co-op': 30342, 'Strategy': 30189, 'Military': 28762, 'War': 28060, 'Difficult': 26037, 'Trading': 25813, 'Realistic': 25497, 'Fast-Paced': 25369, 'Moddable': 6667}}

In [22]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("muhammadaqeelkabir/steam-games-dataset-steamspy-api")

print("Path to dataset files:", path)

Downloading to C:\Users\82109\.cache\kagglehub\datasets\muhammadaqeelkabir\steam-games-dataset-steamspy-api\1.archive...

100%|██████████| 434k/434k [00:00<00:00, 1.72MB/s]

Extracting files...
Path to dataset files: C:\Users\82109\.cache\kagglehub\datasets\muhammadaqeelkabir\steam-games-dataset-steamspy-api\versions\1

In [25]:
import pandas as pd

df = pd.read_csv("C:/Users/82109/.cache/kagglehub/datasets/muhammadaqeelkabir/steam-games-dataset-steamspy-api/versions/1/steam_games_dataset.csv")

df

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,NaN,7642084,1173003,0,"100,000,000 .. 200,000,000",33852,708,6645,301,0,0,0,1013936
1,1172470,Apex Legends,Respawn,Electronic Arts,NaN,668053,326926,0,"100,000,000 .. 200,000,000",10506,496,935,246,0,0,0,124262
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",NaN,1520457,1037487,0,"100,000,000 .. 200,000,000",23165,717,5622,261,0,0,0,314682
3,1623730,Palworld,Pocketpair,Pocketpair,NaN,358266,22443,0,"50,000,000 .. 100,000,000",3854,835,2213,257,2999,2999,0,18028
4,440,Team Fortress 2,Valve,Valve,NaN,1044264,117208,0,"50,000,000 .. 100,000,000",21244,736,4262,102,0,0,0,43819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,444720,Inexistence,Jonathan BRASSAUD,Jonathan BRASSAUD,NaN,242,126,0,"50,000 .. 100,000",279,0,313,0,299,299,0,0
9996,649600,Swords and Sandals 2 Redux,Whiskeybarrel Studios,eGames.com,NaN,429,117,0,"50,000 .. 100,000",333,0,432,0,999,999,0,4
9997,1122120,STATIONflow,DMM GAMES,DMM GAMES,NaN,414,66,0,"50,000 .. 100,000",984,0,984,0,1799,1799,0,6
9998,424640,Karaski: What Goes Up...,Unbound Creations,Unbound Creations,NaN,51,8,0,"50,000 .. 100,000",0,0,0,0,1199,1199,0,0
9999,598060,Slasher's Keep,Damian Schloter,Damian Schloter,NaN,1791,355,0,"50,000 .. 100,000",423,0,396,0,1399,1399,0,6

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            10000 non-null  int64
 1   name             10000 non-null  object
 2   developer        9967 non-null   object
 3   publisher        9946 non-null   object
 4   score_rank       5 non-null      float64
 5   positive         10000 non-null  int64
 6   negative         10000 non-null  int64
 7   userscore        10000 non-null  int64
 8   owners           10000 non-null  object
 9   average_forever  10000 non-null  int64
 10  average_2weeks   10000 non-null  int64
 11  median_forever   10000 non-null  int64
 12  median_2weeks    10000 non-null  int64
 13  price            10000 non-null  int64
 14  initialprice     10000 non-null  int64
 15  discount         10000 non-null  int64
 16  ccu              10000 non-null  int64
dtypes: float64(1), int64(12), object(4)
memory usage: 1.3+ MB